### ISSUE TITLE
Market Order does not set Stop Loss and Take Profit

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida-cTrader#15]
Setting a Limit Order works fine like described below:
```
acc.placeOrder({
    direction: MidaOrderDirection.SELL,
    volume: 2.6,
    symbol: 'GER40',
    limit: 14500,
    protection: {
        stopLoss: 14520,
        takeProfit: 14400
    }
})
```

However if the order has no Limit and I want it to be a Market order, the stopLoss and takeProfit are not taken into account and I only see a simple position in cTrader.

**Comment by dbvcode** [comment]
After posting I looked at the code and found this,
[https://github.com/Reiryoku-Technologies/Mida-cTrader/blob/f14111fd604c09d3e844e6ec51ea175d29c8f7d4/src/core/platforms/ctrader/CTraderAccount.ts#L640](https://github.com/Reiryoku-Technologies/Mida-cTrader/blob/f14111fd604c09d3e844e6ec51ea175d29c8f7d4/src/core/platforms/ctrader/CTraderAccount.ts#L640)

I know it's possible to modify an order on cTrader. Is there a function to do so?
I mean, place the market order, wait for it to get filled, get the orderId and then edit that order and add the stopLoss and takeProfit.

**Comment by Vasile-Peste** [comment]
I'm working on the next version to make the protection work even when you make a market order. Even if cTrader doesn't allow this, it can be easily implemented as a request after order execution.

You can change open positions, check the [positions documentation](https://www.mida.org/documentation/trading/positions.html)

**Comment by Vasile-Peste** [comment]
Fixed with https://github.com/Reiryoku-Technologies/Mida-cTrader/pull/18

**Comment by dbvcode** [comment]
Cool!
On this note an issue that might arise.
If you get a worse fill than expected your StopLoss and TakeProfit will be off.
I think for this a good idea is to have the the SL and TP in points or ticks and be computed after the order gets filled.
Having it in points opens Pandora's box though because they differ for every market related to the decimal places.

**Comment by dbvcode** [comment]
Could it be that after this update there is a way for the orders to get doubled?
Sounds funny, I know. But I updated the lib last week and I've been away so did not quite test it.
Today I saw if I do a limit order with the protection when it gets triggered and turns into a position I end up with 2 identical positions at the exact same time on cTrader.
@Vasile-Peste is you think there might be an issue here I can try to isolate the problem.
It's really funny and annoying.

**Comment by Vasile-Peste** [comment]
Hey, are you still able to reproduce this with [Mida 2022.1](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.1.0) and [Mida cTrader 5](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.0.0)? Let me know please, so I can address the issue deeper, thank you!

**Comment by dbvcode** [comment]
If I try it with the latest Mida and Mida cTrader I now get
Unknown payload type 2142

**Comment by Vasile-Peste** [comment]
This is because you created a new access token without trading permissions, try creating a new one with trading permissions and let me know!

**Comment by dbvcode** [comment]
My bad! Just reissued the (wrong) token and didn't know. 

Protection does work on market order!
Awesome!
Do you do it, after the trade is executed? Or is it sent directly to cTrader with the original order?

**Comment by dbvcode** [comment]
It works!
