### ISSUE TITLE
getPendingOrders() not returning pending orders

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida-cTrader#26]
I have one pending order that I can see if I do `account.getOrders('GER40')`.
It's status is `'pending'`.
But if I do `account.getPendingOrders()` the array of orders is empty.
This is the first time I use this function so I don't know if it used to work or not.
I am using Mida-cTrader v5.0.2

**Comment by Vasile-Peste** [comment]
You are right, pending orders were not fetched during the account login and preload. Fixed with [v5.1.0](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.1.0). Let me know if it works! Thank you!

**Comment by dbvcode** [comment]
Works! Good job!
