### ISSUE TITLE
period-update vs period-close different values

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida-cTrader#27]
The problem is period-update ends with a candle that's different than the one that comes right after, for the same timestamp, on period-close.
It seems that period-update is missing data when a new period/timestamp is created.
This is a minimal working example of how to spot the error:

```
  const klines: KlineDBModel = {};

  marketWatcher.on("period-close", (event) => {
      const candle = event.descriptor.period as MidaPeriod;
      const existing = klines[candle.startDate.valueOf().toString()];
      if (existing) {
          const closeD = candle.close.toString() !== existing.close;
          const openD = candle.open.toString() !== existing.open;
          const highD = candle.high.toString() !== existing.high;
          const lowD = candle.low.toString() !== existing.low;
          const volD = candle.volume.toString() !== existing.volume;

          if (closeD || openD || highD || lowD || volD) {
              const msg = `${formateDateTime()} existing vs period-close,\n` +
                  `o: ${existing.open} ^ ${candle.open.toString()}` + (openD ? ' x' : '') +
                  `\nc: ${existing.close} ^ ${candle.close.toString()}` + (closeD ? ' x' : '') +
                  `\nl: ${existing.low} ^ ${candle.low.toString()}` + (lowD ? ' x' : '') +
                  `\nh: ${existing.high} ^ ${candle.high.toString()}` + (highD ? ' x' : '') +
                  `\nv: ${existing.volume} ^ ${candle.volume.toString()}` + (volD ? ' x' : '');

              console.error(msg);
          }
      }

      klines[candle.startDate.valueOf().toString()] = {
          close: candle.close.toString(),
          high: candle.high.toString(),
          open: candle.open.toString(),
          low: candle.low.toString(),
          volume: candle.volume.toString()
      };
  });

  marketWatcher.on("period-update", (event) => {
      const candle = event.descriptor.period as MidaPeriod;
      klines[candle.startDate.valueOf().toString()] = {
          close: candle.close.toString(),
          high: candle.high.toString(),
          open: candle.open.toString(),
          low: candle.low.toString(),
          volume: candle.volume.toString()
      };
  });

  interface KlineDBModel {
      [key: string]: { //timestamp
        open: string;
        high: string;
        low: string;
        close: string;
        volume: string;
      };
    
```

My broker is Pepperstone and I always check GER40 but I have the feeling it's not broker related. Who knows?

**Comment by Vasile-Peste** [comment]
This is because with "if (closeD || openD || highD || lowD || volD)" ... you are comparing the newly created candlestick with the closed one.

This happens because currently closed periods are detected by leveraging the `getSymbolPeriods()` method (https://www.mida.org/documentation/candlesticks/get-symbol-periods.html). So this is not really real time, the call is made every 1 minute + some seconds of delay to allow cTrader saving the closed periods in their database.

Meanwhile `period-update` is triggered in real time among with new market ticks.
So what is happening in your code is that when a period is closed, new period updates are triggered right after and you save them in `klines` and after the delay of some seconds, you are checking the closed period with the new opened period in `klines`, getting wrong data.

Anyway I'm preparing some improvements in order to make the `period-close` event real time. So stay tuned.

**Comment by dbvcode** [comment]
Code explanation:
- `period-update` always updates the `klines` at the timestamp-s key.
- When a new period hits `period-update`, a new key is inserted.
- If the key already exists it gets updated
- When `period-update` spits a new timestamp(`candleStart`) the process starts again
- When `period-close` emits the value(with delay and when there is already a value at that timestamp) I get the existing value
- The existing value in theory should be the LAST emit of the `period-close` for that timestamp
- And here I compare the existing period(which is not the last) in `klines` with the delayed and closed one from `period-close`

And in my case I get differences and it seems the `period-update`'s last value was missing data!
This is the output for the above code for me, GER40 on Pepperstone
Values on the left are the last emission of period-close for the timestamp of the closed candle from period-close
As you can see the timestamp is the same, but the values are different.
On another note, this code will create a succession of key pair candles in a timely fashion with the candle values inside.


```
12/08/2022 13:50 existing vs period-close,
o: 13738.2 ^ 13738.2
c: 13750.4 ^ 13747.9 x
l: 13738.2 ^ 13738.2
h: 13750.4 ^ 13751.4 x
v: 288 ^ 374 x
```

```
12/08/2022 13:55 existing vs period-close,
o: 13747.4 ^ 13747.4
c: 13750.9 ^ 13755.2 x
l: 13745 ^ 13745
h: 13750.9 ^ 13755.8 x
v: 252 ^ 302 x
```

```
12/08/2022 14:00 existing vs period-close,
o: 13754.7 ^ 13754.7
c: 13744.7 ^ 13741.7 x
l: 13741.9 ^ 13740.7 x
h: 13755.2 ^ 13755.2
v: 272 ^ 344 x
```

**Comment by Vasile-Peste** [comment]
Unfortunately I was not able to reproduce your issue (on ICMarkets). Anyway, with [Mida 2022.4](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.4.0) and [Mida cTrader 5.2](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.2.0) the `period-close` event had some changes and now is fired more quickly without any internal delay. Could you try again and let me know if the "issue" persists? In that case I will try to reproduce with your broker. Thank you!

**Comment by dbvcode** [comment]
This issue has been fixed with the latest version of Mida to date that uses the candle-close event from cTrader
