### ISSUE TITLE
.getSymbolPeriods() gets only 68 candles

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida-cTrader#35]
I just found out on Pepperstone if I do account.getSymbolPeriods() for 1H candles I only get 68.
On the 5m chart I get about 500 or even more.
Is this a bug? Maybe a parameter that can be sent to cTrader to give us X amount of candles?

**Comment by Vasile-Peste** [comment]
This works properly now with [Mida cTrader 5.4](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.4.0), basically the cTrader Open API limits the timeframe in which to search for candles, and it is limited based on the timeframe we are requesting, this "fix" is just an adaptation to their rules, so now for every timeframe you should get a decent amount of candles independently of the requested timeframe.
