### ISSUE TITLE
Get Older Trades

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida-cTrader#37]
Currently, I can retrieve only the most recent trades from the `getTrades()` method. 
Since I'm opening a lot of orders I can get only 2-day-old trades.

Can we have other ways to fetch the older trades?

For example, it would be useful getting a trade by the order id.
Or at least have something like pagination in the `getTrades()` method?

(btw trades or executedTrades don't seem to work)

**Comment by Vasile-Peste** [comment]
Hello, with [Mida cTrader 5.4](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.4.0), now `getTrades()` returns the trades of the last two weeks!

I'm still working to design an API for getting historical data with timestamps given as input, hopefully what we have now is enough.
