### ISSUE TITLE
Error on authentication

### ISSUE THREAD

**Issue by Robbby-00** [Reiryoku-Technologies/Mida-cTrader#38]
Hi, I followed this [guide](https://www.mida.org/posts/how-to-use-mida-with-ctrader/) to get all the data needed to login.

But once run the following code:

```
import { info, Mida } from "@reiryoku/mida"
import { CTraderPlugin } from "@reiryoku/mida-ctrader"

Mida.use(new CTraderPlugin());


async function test() {
    const account = await Mida.login("cTrader", {
        clientId: "***",
        clientSecret: "***",
        accessToken: "***",
        cTraderBrokerAccountId: "***",
    });

    info(await account.getBalance())
}

test();
```

I got this error:

```
node_modules\@reiryoku\mida-ctrader\build\src\core\platforms\ctrader\CTraderApplication.js:80
                throw new Error();
                      ^

Error
    at CTraderApplication.<anonymous> (node_modules\@reiryoku\mida-ctrader\build\src\core\platforms\ctrader\CTraderApplication.js:80:23)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules\@reiryoku\mida-ctrader\build\src\core\platforms\ctrader\CTraderApplication.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Does anyone have any idea what the error could be?

**Comment by Vasile-Peste** [comment]
Hello, first of all we are sorry for the error not showing any useful message, this will be addressed. Second, this error is raised when the cTraderBrokerAccountId you passed in not found among the trading accounts authorised on cTrader Open API. Can you double check that you have the permissions to access that account?

**Comment by Robbby-00** [comment]
Thanks, that was a stupid mistake, I swaped accountId and accountNumber

Thanks for your help
