### ISSUE TITLE
Unknown payload type 2142

### ISSUE THREAD

**Issue by soutionscience** [Reiryoku-Technologies/Mida-cTrader#5]
Hi ,
Followed the instructions to placeOrder, getting error "Unknown payload type 2142".
myOrder.isRejected is empty ...

**Comment by Vasile-Peste** [comment]
Hi, ths is a duplicate of https://github.com/Reiryoku-Technologies/Mida-cTrader/issues/4, most probably you are using an access token without trading permissions. I will try to display a more detailed error message in this case
