### ISSUE TITLE
Errors when positions are fulfilled

### ISSUE THREAD

**Issue by hesedel** [Reiryoku-Technologies/Mida-cTrader#7]
When placing stop orders and I came across this issue where when the position was made and the stop-loss/take-profit was triggered OR if a 2nd order is placed I get this error:

```
@reiryoku/mida/build/src/core/positions/MidaBrokerPosition.js:120
        return this.firstFilledOrder.brokerAccount;
                                     ^

TypeError: Cannot read property 'brokerAccount' of undefined
```

I Also alternatively get this error `cannot get .toString() of undefined` when normal MARKET order is fulfilled:
and it has to do with this part of code in `CtraderBrokerAccount.ts`
```
deal.orderId.toString() === id

**Comment by Vasile-Peste** [comment]
Fixed with https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v2.0.0
